-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
--
-- Sample keymap
-- map("n", "<leader>l", "<cmd>:Lazy<cr>", { desc = "Lazy" })
